/* Original colors
var color1="rgb(2, 200, 255)"; 
var color2= "#FF6600";
*/

var color1="rgb(2, 200, 255)"; 
var color2= "#FF6600";

var crypto_name_matrix1, crypto_name_matrix2;

var M_CAP_ordered_list = ["Bitcoin", "Ethereum", "Bitcoin Cash", "Ripple", "Dash", "Litecoin", "NEM", "IOTA", "Monero", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Bytecoin", "Decred", "BitShares", "Stellar Lumens", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Dogecoin", "Blocknet", "Syscoin", "Verge", "FirstCoin", "Nxt", "I-O Coin", "Ubiq", "Particl", "NAV Coin", "Rise", "Vertcoin", "Bitdeal", "FairCoin", "Metaverse ETP", "Gulden", "ZCoin", "CloakCoin", "NoLimitCoin", "Elastic", "Peercoin", "Aidos Kuneen", "ReddCoin", "LEOcoin", "Counterparty", "MonaCoin", "DECENT", "The ChampCoin", "Viacoin", "Emercoin", "Crown", "Sprouts", "ION", "Namecoin", "Clams", "BitBay", "OKCash", "Unobtanium", "Diamond", "Skycoin", "MonetaryUnit", "SpreadCoin", "Mooncoin", "Expanse", "SIBCoin", "ZenCash", "PotCoin", "Radium", "Burst", "LBRY Credits", "Shift", "DigitalNote", "Neblio", "Einsteinium", "Compcoin", "Omni", "ATC Coin", "Energycoin", "Rubycoin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "BlackCoin", "Golos", "GridCoin"]

var SIMIL_CARD_ordered_list = ["Decred", "BitBay", "Factom", "Gambit", "Radium", "Ethereum", "Ethereum Classic", "Shift", "MonetaryUnit", "Energycoin", "Expanse", "Lykke", "Waves", "Dash", "Ubiq", "Syscoin", "Einsteinium", "Viacoin", "Burst", "PotCoin", "GameCredits", "Stratis", "NEM", "Litecoin", "Unobtanium", "BitcoinDark", "Bitcoin", "Diamond", "Vertcoin", "Omni", "Crown", "ReddCoin", "BlackCoin", "SpreadCoin", "FirstCoin", "Siacoin", "Nexus", "Monero", "GridCoin", "Blocknet", "Ripple", "Counterparty", "FairCoin", "I-O Coin", "BitConnect", "Nxt", "Dogecoin", "Bytecoin", "SaluS", "Clams", "PIVX", "Gulden", "Verge", "BitShares", "DigitalNote", "Namecoin", "ION", "Peercoin", "DigiByte", "CloakCoin", "Byteball Bytes", "MonaCoin", "Ark", "Aidos Kuneen", "NAV Coin", "Komodo", "Stellar Lumens", "Lisk", "Groestlcoin", "LBRY Credits", "SIBCoin", "Mooncoin", "Emercoin", "NoLimitCoin", "ZCoin", "Steem", "Zcash", "NEO", "IOTA", "Golos", "E-coin", "Rubycoin", "ATC Coin", "Compcoin", "Neblio", "ZenCash", "Skycoin", "OKCash", "Sprouts", "The ChampCoin", "DECENT", "LEOcoin", "Elastic", "Metaverse ETP", "Bitdeal", "Rise", "Particl", "GXShares", "Hshare", "Bitcoin Cash"]
var SIMIL_CARD_ordered_list_test = ["Ethereum", "Ethereum Classic", "Shift", "MonetaryUnit", "Decred", "BitBay", "Factom", "Gambit", "Radium",  "Energycoin", "Expanse", "Lykke", "Waves", "Dash", "Ubiq", "Syscoin", "Einsteinium", "Viacoin", "Burst", "PotCoin", "GameCredits", "Stratis", "NEM", "Litecoin", "Unobtanium", "BitcoinDark", "Bitcoin", "Diamond", "Vertcoin", "Omni", "Crown", "ReddCoin", "BlackCoin", "SpreadCoin", "FirstCoin", "Siacoin", "Nexus", "Monero", "GridCoin", "Blocknet", "Ripple", "Counterparty", "FairCoin", "I-O Coin", "BitConnect", "Nxt", "Dogecoin", "Bytecoin", "SaluS", "Clams", "PIVX", "Gulden", "Verge", "BitShares", "DigitalNote", "Namecoin", "ION", "Peercoin", "DigiByte", "CloakCoin", "Byteball Bytes", "MonaCoin", "Ark", "Aidos Kuneen", "NAV Coin", "Komodo", "Stellar Lumens", "Lisk", "Groestlcoin", "LBRY Credits", "SIBCoin", "Mooncoin", "Emercoin", "NoLimitCoin", "ZCoin", "Steem", "Zcash", "NEO", "IOTA", "Golos", "E-coin", "Rubycoin", "ATC Coin", "Compcoin", "Neblio", "ZenCash", "Skycoin", "OKCash", "Sprouts", "The ChampCoin", "DECENT", "LEOcoin", "Elastic", "Metaverse ETP", "Bitdeal", "Rise", "Particl", "GXShares", "Hshare", "Bitcoin Cash"]

var similarities_grades_MCAP_ordered = [18, 32, 1, 12, 24, 19, 20, 2, 13, 29, 2, 11, 3, 2, 20, 25, 4, 2, 10, 35, 7, 3, 1, 3, 8, 34, 5, 13, 13, 6, 18, 20, 1, 25, 10, 12, 22, 7, 13, 10, 11, 23, 1, 3, 1, 16, 1, 11, 1, 7, 2, 5, 2, 1, 6, 3, 15, 1, 11, 4, 1, 1, 21, 2, 15, 1, 6, 6, 9, 34, 1, 18, 17, 1, 27, 14, 2, 26, 2, 1, 20, 32, 20, 2, 27, 6, 1, 21, 1, 15, 1, 26, 1, 33, 1, 9, 2, 14, 1, 12]

var name_arr_alp_sorted = ["ATC Coin", "Aidos Kuneen", "Ark", "BitBay", "BitConnect", "BitShares", "Bitcoin", "Bitcoin Cash", "BitcoinDark", "Bitdeal", "BlackCoin", "Blocknet", "Burst", "Byteball Bytes", "Bytecoin", "Clams", "CloakCoin", "Compcoin", "Counterparty", "Crown", "DECENT", "Dash", "Decred", "Diamond", "DigiByte", "DigitalNote", "Dogecoin", "E-coin", "Einsteinium", "Elastic", "Emercoin", "Energycoin", "Ethereum", "Ethereum Classic", "Expanse", "Factom", "FairCoin", "FirstCoin", "GXShares", "Gambit", "GameCredits", "Golos", "GridCoin", "Groestlcoin", "Gulden", "Hshare", "I-O Coin", "ION", "IOTA", "Komodo", "LBRY Credits", "LEOcoin", "Lisk", "Litecoin", "Lykke", "Metaverse ETP", "MonaCoin", "Monero", "MonetaryUnit", "Mooncoin", "NAV Coin", "NEM", "NEO", "Namecoin", "Neblio", "Nexus", "NoLimitCoin", "Nxt", "OKCash", "Omni", "PIVX", "Particl", "Peercoin", "PotCoin", "Radium", "ReddCoin", "Ripple", "Rise", "Rubycoin", "SIBCoin", "SaluS", "Shift", "Siacoin", "Skycoin", "SpreadCoin", "Sprouts", "Steem", "Stellar Lumens", "Stratis", "Syscoin", "The ChampCoin", "Ubiq", "Unobtanium", "Verge", "Vertcoin", "Viacoin", "Waves", "ZCoin", "Zcash", "ZenCash"]


var SIMIL_CARD_ordered_list1 = ["Factom", "BitBay", "Ethereum", "Decred", "Radium", "Gambit", "MonetaryUnit", "Ethereum Classic", "Lykke", "Expanse", "Ubiq", "Dash", "Waves", "Shift", "Syscoin", "Viacoin", "Litecoin", "NEM", "GameCredits", "Einsteinium", "Bitcoin", "Stratis", "PotCoin", "Burst", "Unobtanium", "BitcoinDark", "Vertcoin", "ReddCoin", "Nexus", "Siacoin", "Diamond", "SpreadCoin", "Monero", "Crown", "Omni", "FirstCoin", "Counterparty", "BlackCoin", "Ripple", "BitConnect", "Blocknet", "Verge", "Nxt", "FairCoin", "PIVX", "Dogecoin", "MonaCoin", "BitShares", "GridCoin", "Bytecoin", "Peercoin", "Energycoin", "Clams", "Byteball Bytes", "DigiByte", "CloakCoin", "Emercoin", "Namecoin", "DigitalNote", "Zcash", "Ark", "Steem", "Stellar Lumens", "Hshare", "Komodo", "NAV Coin", "SIBCoin", "LBRY Credits", "IOTA", "NEO", "Lisk", "NoLimitCoin", "ION", "SaluS", "Groestlcoin", "Bitcoin Cash", "GXShares", "I-O Coin", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "Gulden", "ZCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "OKCash", "Skycoin", "Mooncoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]

var similarities_grades_MCAP_ordered1 = [20,36,1,12,24,22,22,2,14,29,2,12,2,3,20,24,3,3,8,36,9,3,3,3,10,37,6,15,15,6,16,22,1,28,10,12,23,11,13,11,1,25,1,3,1,16,1,11,1,1,1,6,2,1,8,1,16,1,13,10,1,1,23,6,14,1,2,6,7,37,1,18,15,1,30,15,1,28,3,1,20,34,19,3,24,6,1,21,1,14,1,8,1,33,1,2,2,13,1,9]

//close high low mc open volume - t0, t2015, t2016, t2017
var matrix_of_simil_CARD = [[18,32,1,12,24,19,20,2,14,29,2,11,3,2,20,25,4,2,10,35,7,3,1,3,8,34,5,13,13,6,18,20,1,25,10,12,22,7,14,10,11,23,1,3,1,16,1,11,1,7,2,5,2,1,6,3,15,1,11,4,1,1,21,2,15,1,6,6,9,34,1,18,17,1,27,14,2,26,2,1,20,32,20,2,27,6,1,21,1,15,1,26,1,33,1,9,2,14,1,12],
[20,36,1,12,24,22,22,2,14,29,2,12,2,3,20,24,3,3,8,36,9,3,3,3,10,37,6,15,15,6,16,22,1,28,10,12,23,11,13,11,1,25,1,3,1,16,1,11,1,1,1,6,2,1,8,1,16,1,13,10,1,1,23,6,14,1,2,6,7,37,1,18,15,1,30,15,1,28,3,1,20,34,19,3,24,6,1,21,1,14,1,8,1,33,1,2,2,13,1,9],
[19,32,1,12,25,19,20,1,12,29,1,11,6,2,22,26,3,2,14,33,7,3,1,6,9,32,6,14,14,6,17,18,1,25,9,12,25,7,13,9,11,23,1,3,1,20,1,11,1,6,1,4,1,1,6,1,10,1,12,4,1,1,22,1,15,1,6,6,8,32,1,19,16,1,28,15,3,25,3,1,19,30,19,2,29,7,1,21,1,14,1,24,1,32,1,13,3,13,1,12],
[19,34,1,9,24,27,15,1,13,23,1,12,9,27,19,22,4,3,9,34,7,5,1,3,7,33,9,13,13,7,15,17,1,13,10,12,20,5,11,8,12,21,1,1,1,20,1,11,1,7,8,5,2,1,5,1,11,1,8,13,1,1,22,2,16,1,7,4,21,29,1,19,15,1,25,12,4,29,2,1,18,29,18,11,23,5,1,20,1,12,1,26,1,33,1,8,2,11,1,10 ],
[18,32,1,12,24,19,20,1,13,30,1,11,2,2,21,25,3,2,10,35,8,3,1,3,8,35,5,13,13,6,18,20,1,26,10,12,22,7,14,11,11,23,1,3,1,17,1,11,1,6,2,4,2,1,6,1,15,1,12,4,1,1,22,2,15,1,6,6,9,34,1,18,16,1,27,14,2,26,2,1,20,33,20,2,27,6,1,22,1,15,1,26,1,33,1,8,2,14,1,12],
[50,31,6,10,28,27,20,6,18,10,12,17,17,25,18,37,3,15,4,11,12,5,12,2,9,12,6,13,13,10,3,38,3,18,15,17,22,25,12,1,6,19,3,8,3,7,3,3,4,14,9,6,15,2,14,3,17,7,20,21,6,3,9,27,4,1,2,7,4,20,1,18,2,1,3,9,7,3,1,9,2,6,4,19,23,33,20,4,3,1,1,3,2,14,7,1,3,10,1,1],

[2,1,1,10,3,6,1,1,2,1,1,1,1,1,1,1,1,1,3,1,10,9,1,1,1,1,1,1,1,1,1,1,1,1,6,5,2,1,1,9,7,1,1,3,1,5,1,3,1,3,1,3,1,1,4,1,4,1,7,3,1,1,9,1,1,1,1,3,1,2,1,5,1,1,2,1,8,1,1,1,7,1,9,1,1,4,1,10,1,1,1,4,5,1,1,1,4,5,1,1],
[3,1,1,9,3,6,1,1,3,1,1,1,1,1,1,1,1,1,2,1,10,9,1,1,1,1,1,1,1,1,1,1,1,1,6,6,3,1,1,5,5,1,1,4,1,4,1,5,1,1,1,3,1,1,4,1,6,1,7,2,1,1,10,1,1,1,1,4,1,2,1,5,1,1,3,1,7,1,1,1,10,1,9,1,1,1,1,10,1,1,1,4,4,1,1,1,4,7,1,1],
[2,1,1,9,3,6,1,1,2,1,1,1,1,1,1,1,1,1,2,1,9,9,1,1,1,1,1,1,1,1,1,1,1,1,5,5,3,1,1,9,5,1,1,3,1,6,1,2,1,2,1,3,1,1,4,1,8,1,8,3,1,1,9,1,1,1,1,3,1,2,5,4,1,1,2,1,6,1,1,1,4,1,10,1,1,4,1,10,1,1,1,4,6,1,1,1,5,5,1,1],
[4,1,1,8,3,8,1,1,3,1,1,1,1,1,1,1,1,1,5,1,7,5,1,1,1,1,1,1,1,1,1,1,1,1,6,2,1,6,1,9,8,1,1,3,1,4,1,1,1,4,1,4,1,1,4,1,6,1,8,5,1,1,8,1,1,1,1,4,3,2,3,4,1,1,2,1,6,1,1,1,3,1,5,1,1,5,1,9,1,1,1,5,6,1,1,1,5,5,1,1],
[2,1,1,9,3,6,1,1,2,1,1,1,1,1,1,1,1,1,3,1,10,10,1,1,1,1,1,1,1,1,1,1,1,1,6,5,2,1,1,9,6,1,1,3,1,4,1,3,1,2,1,3,1,1,4,1,8,1,8,3,1,1,9,1,1,1,1,3,1,2,1,4,1,1,2,1,8,1,1,1,6,1,10,1,1,4,1,10,1,1,1,3,5,1,1,1,4,5,1,1],
[7,1,1,8,7,8,1,1,4,1,1,1,1,1,1,1,1,1,3,1,4,11,1,1,1,1,1,1,1,1,1,1,1,1,14,1,2,2,1,11,3,1,1,5,1,2,1,6,1,1,1,2,1,1,11,1,7,1,4,6,1,1,7,1,1,1,1,7,1,2,1,4,1,1,3,1,9,1,1,1,5,1,1,1,1,2,1,3,1,1,1,2,3,1,1,1,1,9,1,1],

[8,3,1,1,12,1,2,1,14,1,1,1,1,1,1,1,1,1,9,1,2,1,1,1,1,12,1,4,4,1,4,4,1,1,1,13,3,1,1,3,19,1,1,16,1,1,1,8,1,6,1,2,1,1,3,1,2,8,14,3,1,1,16,2,1,1,1,3,1,9,11,1,1,1,4,1,1,2,2,1,8,1,17,1,3,9,1,14,1,5,1,7,1,1,1,1,1,1,1,1],
[8,4,1,1,12,1,3,1,13,1,1,1,1,1,1,1,1,1,10,1,2,1,1,1,1,12,1,4,4,1,4,4,1,1,1,13,5,1,1,3,19,1,1,16,1,1,1,12,1,8,1,2,1,1,3,1,4,1,14,3,1,1,15,2,1,1,1,3,1,9,12,1,1,1,1,1,1,1,2,1,8,1,17,1,5,10,1,12,1,3,1,7,1,1,1,1,1,1,1,1],
[7,3,1,1,9,1,2,1,13,1,1,1,1,1,1,1,1,1,9,1,2,1,1,1,1,13,1,3,3,1,2,4,1,1,1,14,2,1,1,3,17,1,1,15,1,1,1,7,1,4,1,2,1,1,3,1,2,16,12,3,1,1,16,2,1,1,1,3,1,8,12,1,1,1,14,1,1,2,2,1,8,1,16,1,3,7,1,14,1,5,1,8,1,1,1,1,1,1,1,1],
[6,2,1,1,13,2,3,1,12,1,1,1,1,1,1,1,1,1,7,1,1,7,1,1,1,13,1,4,4,1,4,4,1,1,1,14,6,1,1,3,18,1,1,14,1,1,1,5,1,5,1,1,1,1,3,1,2,0,12,3,1,1,15,2,1,1,1,3,1,8,12,1,1,1,5,1,1,8,1,1,8,1,16,1,5,7,1,13,1,3,1,7,1,1,1,1,1,1,1,1],
[7,3,1,1,12,1,2,1,13,1,1,1,1,1,1,1,1,1,11,1,2,1,1,1,1,12,1,4,4,1,4,4,1,1,1,13,3,1,1,3,20,1,1,16,1,1,1,10,1,6,1,2,1,1,3,1,2,3,13,3,1,1,15,2,1,1,1,3,1,9,12,1,1,1,5,1,1,2,2,1,9,1,17,1,3,10,1,14,1,5,1,7,1,1,1,1,1,1,1,1],
[9,7,1,7,8,5,8,1,10,1,1,1,1,1,1,1,1,1,4,1,8,4,1,1,1,8,1,3,3,1,1,3,1,1,4,5,3,7,1,11,9,1,1,8,1,4,1,7,1,5,1,7,1,1,4,1,3,6,10,5,1,1,8,4,1,1,1,10,7,7,4,4,3,1,5,1,2,4,5,1,3,1,7,1,13,4,1,2,1,3,1,5,3,1,1,1,1,7,1,7],

[11,19,1,2,11,7,7,1,5,14,1,1,7,22,12,16,1,24,2,15,7,2,1,1,2,20,4,2,2,1,1,1,1,21,6,10,8,2,1,13,4,1,1,1,1,12,1,5,1,13,1,1,2,1,4,1,6,1,12,5,1,1,4,9,3,1,1,4,7,19,1,12,10,1,6,8,1,15,1,1,8,21,6,13,14,3,1,8,1,11,1,6,1,16,1,4,1,11,1,9],
[11,21,1,4,13,9,8,1,5,16,1,1,7,25,13,16,1,25,4,14,7,2,1,1,4,20,4,2,2,1,1,1,1,22,8,10,6,3,1,14,1,1,1,1,1,12,1,7,1,1,1,1,2,1,5,1,7,1,12,3,1,1,8,10,4,1,1,4,4,20,1,11,9,1,10,9,1,18,1,1,12,20,6,11,12,3,1,8,1,7,1,1,1,13,1,1,1,12,1,5],
[11,18,1,2,11,9,7,1,5,13,1,1,6,23,12,17,1,25,5,15,7,1,1,1,2,20,3,2,2,1,1,1,1,19,7,9,7,1,1,11,4,1,1,1,1,14,1,5,1,13,1,1,1,1,4,1,8,1,13,3,1,1,6,9,2,1,1,4,7,18,1,11,11,1,7,8,3,15,2,1,7,19,8,10,15,4,1,6,1,12,1,6,1,14,1,4,2,11,1,10],
[12,21,1,2,11,8,8,1,5,13,1,1,7,23,13,16,1,23,3,21,6,2,1,1,2,19,11,2,2,1,1,1,1,8,6,9,7,2,1,12,4,1,1,1,1,11,1,4,1,13,4,1,2,1,4,1,8,1,10,5,1,1,7,7,5,1,1,4,7,17,1,13,9,1,7,8,3,16,1,1,8,20,6,11,12,4,1,7,1,9,1,9,1,16,1,4,1,9,1,8],
[10,19,1,2,11,6,7,1,5,13,1,1,7,23,12,17,1,24,3,15,7,2,1,1,2,20,4,2,2,1,1,1,1,21,7,10,8,2,1,13,4,1,1,1,1,13,1,5,1,13,1,1,2,1,4,1,7,1,12,5,1,1,3,8,2,1,1,4,6,19,1,12,10,1,6,8,1,15,1,1,8,21,6,12,14,3,1,9,1,11,1,7,1,15,1,4,1,12,1,9],
[26,15,1,3,10,17,9,1,13,9,7,1,16,24,15,25,1,12,3,3,8,4,1,1,2,8,6,2,2,2,1,2,1,22,9,12,14,16,1,1,3,1,1,10,5,2,1,3,1,23,6,5,10,1,8,1,12,1,9,13,1,1,7,14,3,1,1,4,2,11,2,6,1,1,2,7,8,1,1,1,1,4,4,18,17,16,1,2,1,1,1,3,1,3,1,1,3,5,1,1]]


Matrix_of_names_CARD = [
    ["Decred", "Factom", "BitBay", "Gambit", "Ethereum", "Radium", "Ethereum Classic", "MonetaryUnit", "Shift", "Expanse", "Energycoin", "Waves", "Lykke", "Dash", "Ubiq", "Syscoin", "Viacoin", "Einsteinium", "NEM", "Stratis", "GameCredits", "PotCoin", "Burst", "Litecoin", "Bitcoin", "BitcoinDark", "Unobtanium", "Diamond", "Vertcoin", "ReddCoin", "Crown", "Omni", "Monero", "FirstCoin", "SpreadCoin", "BlackCoin", "Nexus", "Siacoin", "Ripple", "Blocknet", "GridCoin", "BitConnect", "I-O Coin", "FairCoin", "Counterparty", "Bytecoin", "Dogecoin", "Nxt", "Clams", "SaluS", "PIVX", "BitShares", "Verge", "Gulden", "DigiByte", "Peercoin", "ION", "Namecoin", "DigitalNote", "Byteball Bytes", "CloakCoin", "Ark", "MonaCoin", "Lisk", "Stellar Lumens", "Komodo", "NAV Coin", "Aidos Kuneen", "IOTA", "NEO", "Zcash", "Steem", "ZCoin", "NoLimitCoin", "Emercoin", "Mooncoin", "SIBCoin", "LBRY Credits", "Groestlcoin", "Bitcoin Cash", "Hshare", "GXShares", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "Elastic", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "OKCash", "Skycoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]
,
 ["Factom", "BitBay", "Ethereum", "Decred", "Radium", "Gambit", "MonetaryUnit", "Ethereum Classic", "Lykke", "Expanse", "Ubiq", "Dash", "Waves", "Shift", "Syscoin", "Viacoin", "Litecoin", "NEM", "GameCredits", "Einsteinium", "Bitcoin", "Stratis", "PotCoin", "Burst", "Unobtanium", "BitcoinDark", "Vertcoin", "ReddCoin", "Nexus", "Siacoin", "Diamond", "SpreadCoin", "Monero", "Crown", "Omni", "FirstCoin", "Counterparty", "BlackCoin", "Ripple", "BitConnect", "Blocknet", "Verge", "Nxt", "FairCoin", "PIVX", "Dogecoin", "MonaCoin", "BitShares", "GridCoin", "Bytecoin", "Peercoin", "Energycoin", "Clams", "Byteball Bytes", "DigiByte", "CloakCoin", "Emercoin", "Namecoin", "DigitalNote", "Zcash", "Ark", "Steem", "Stellar Lumens", "Hshare", "Komodo", "NAV Coin", "SIBCoin", "LBRY Credits", "IOTA", "NEO", "Lisk", "NoLimitCoin", "ION", "SaluS", "Groestlcoin", "Bitcoin Cash", "GXShares", "I-O Coin", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "Gulden", "ZCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "OKCash", "Skycoin", "Mooncoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]
,
 ["Decred", "Ethereum", "Factom", "BitBay", "Gambit", "Radium", "Ethereum Classic", "Shift", "MonetaryUnit", "Waves", "Dash", "Lykke", "Syscoin", "Expanse", "Energycoin", "Ubiq", "Stratis", "Viacoin", "Einsteinium", "NEM", "Vertcoin", "Bitcoin", "Litecoin", "Unobtanium", "PotCoin", "Burst", "GameCredits", "BitcoinDark", "Diamond", "Crown", "SpreadCoin", "Bytecoin", "Nexus", "Siacoin", "Omni", "FirstCoin", "SaluS", "BlackCoin", "Ripple", "Monero", "Blocknet", "Counterparty", "GridCoin", "BitConnect", "I-O Coin", "FairCoin", "ReddCoin", "PIVX", "Dogecoin", "Nxt", "Clams", "BitShares", "Verge", "DigitalNote", "Lisk", "Komodo", "Byteball Bytes", "DigiByte", "Gulden", "Peercoin", "ION", "Namecoin", "CloakCoin", "MonaCoin", "Ark", "Stellar Lumens", "NAV Coin", "Mooncoin", "SIBCoin", "Groestlcoin", "Zcash", "Steem", "LBRY Credits", "Bitcoin Cash", "IOTA", "NEO", "Hshare", "GXShares", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Sprouts", "OKCash", "Skycoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]
,
 ["Ethereum", "Decred", "Factom", "Gambit", "BitBay", "Expanse", "Radium", "Litecoin", "Zcash", "Energycoin", "MonetaryUnit", "Dash", "Ethereum Classic", "Shift", "Waves", "Viacoin", "Ubiq", "Clams", "Syscoin", "Vertcoin", "Einsteinium", "Bitcoin", "Stratis", "Unobtanium", "PotCoin", "Burst", "GameCredits", "Crown", "NEM", "BitcoinDark", "Diamond", "Monero", "Nexus", "Siacoin", "Lykke", "MonaCoin", "BitConnect", "Blocknet", "I-O Coin", "SpreadCoin", "Omni", "FirstCoin", "FairCoin", "ReddCoin", "LBRY Credits", "BlackCoin", "Dogecoin", "GridCoin", "Ripple", "Lisk", "Bytecoin", "Byteball Bytes", "Nxt", "ZCoin", "Counterparty", "SaluS", "BitShares", "PIVX", "DigiByte", "Gulden", "ION", "Stellar Lumens", "Verge", "CloakCoin", "Peercoin", "DigitalNote", "Ark", "Namecoin", "Mooncoin", "Steem", "Komodo", "NoLimitCoin", "Emercoin", "SIBCoin", "Groestlcoin", "Bitcoin Cash", "IOTA", "NEO", "Hshare", "GXShares", "Particl", "NAV Coin", "Rise", "Bitdeal", "Metaverse ETP", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "OKCash", "Skycoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]
,
 ["Decred", "Factom", "BitBay", "Radium", "Gambit", "Ethereum", "Ethereum Classic", "MonetaryUnit", "Shift", "Lykke", "Expanse", "Energycoin", "Waves", "Dash", "Ubiq", "Syscoin", "Viacoin", "Einsteinium", "Stratis", "NEM", "GameCredits", "PotCoin", "Burst", "Litecoin", "Bitcoin", "BitcoinDark", "Unobtanium", "Vertcoin", "Diamond", "ReddCoin", "Crown", "Omni", "FirstCoin", "SpreadCoin", "BlackCoin", "Monero", "Nexus", "Siacoin", "Ripple", "Blocknet", "Counterparty", "GridCoin", "BitConnect", "Nxt", "I-O Coin", "FairCoin", "Bytecoin", "Dogecoin", "Clams", "BitShares", "PIVX", "SaluS", "Verge", "DigiByte", "Gulden", "Peercoin", "ION", "Namecoin", "DigitalNote", "Byteball Bytes", "CloakCoin", "MonaCoin", "Ark", "Stellar Lumens", "Komodo", "NAV Coin", "Lisk", "Zcash", "Steem", "ZCoin", "NoLimitCoin", "Emercoin", "Mooncoin", "SIBCoin", "LBRY Credits", "Groestlcoin", "Bitcoin Cash", "IOTA", "NEO", "Hshare", "GXShares", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "OKCash", "Skycoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]
,
 ["Bitcoin", "GameCredits", "Waves", "DigitalNote", "Ethereum", "Dash", "Litecoin", "Emercoin", "Zcash", "Verge", "Shift", "Syscoin", "MonaCoin", "NEM", "Counterparty", "BitBay", "Neblio", "Ubiq", "LBRY Credits", "Monero", "Stratis", "Lykke", "Unobtanium", "BitConnect", "Lisk", "Blocknet", "ReddCoin", "Steem", "Dogecoin", "NoLimitCoin", "Gulden", "Peercoin", "Gambit", "Nexus", "Siacoin", "NEO", "BitShares", "Hshare", "Factom", "FirstCoin", "Decred", "Ripple", "Ethereum Classic", "DigiByte", "BlackCoin", "PIVX", "ZCoin", "Viacoin", "SpreadCoin", "ZenCash", "NAV Coin", "Vertcoin", "LEOcoin", "Namecoin", "Mooncoin", "E-coin", "Bitcoin Cash", "IOTA", "Byteball Bytes", "I-O Coin", "CloakCoin", "DECENT", "Radium", "Stellar Lumens", "Bytecoin", "Metaverse ETP", "Crown", "Clams", "Burst", "Einsteinium", "Ark", "BitcoinDark", "GXShares", "Particl", "Rise", "Bitdeal", "FairCoin", "Aidos Kuneen", "The ChampCoin", "MonetaryUnit", "Expanse", "Compcoin", "Energycoin", "Groestlcoin", "Komodo", "Elastic", "ION", "Diamond", "PotCoin", "Rubycoin", "Nxt", "Sprouts", "OKCash", "Skycoin", "SIBCoin", "Omni", "ATC Coin", "SaluS", "Golos", "GridCoin"]
,
 ["Ripple", "BitShares", "Einsteinium", "Stellar Lumens", "Nxt", "Viacoin", "Burst", "Mooncoin", "I-O Coin", "Counterparty", "PotCoin", "Litecoin", "Dogecoin", "Blocknet", "Vertcoin", "Unobtanium", "Rubycoin", "BlackCoin", "Peercoin", "ReddCoin", "DigitalNote", "Energycoin", "Groestlcoin", "Dash", "Bytecoin", "NAV Coin", "FairCoin", "Gulden", "CloakCoin", "MonaCoin", "Namecoin", "Bitcoin", "Monero", "Syscoin", "BitBay", "MonetaryUnit", "Ethereum", "Bitcoin Cash", "NEM", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Crown", "Sprouts", "ION", "Clams", "OKCash", "Diamond", "Skycoin", "SpreadCoin", "Expanse", "SIBCoin", "ZenCash", "Radium", "LBRY Credits", "Shift", "Neblio", "Compcoin", "Omni", "ATC Coin", "Gambit", "E-coin", "SaluS", "Golos", "GridCoin"]
,
 ["BitShares", "Viacoin", "PotCoin", "Einsteinium", "Ripple", "Stellar Lumens", "Burst", "Counterparty", "Mooncoin", "BlackCoin", "Litecoin", "Dogecoin", "Blocknet", "ReddCoin", "Nxt", "I-O Coin", "FairCoin", "Unobtanium", "NAV Coin", "Vertcoin", "Peercoin", "Namecoin", "Energycoin", "Rubycoin", "Groestlcoin", "Bitcoin", "Dash", "Monero", "Syscoin", "CloakCoin", "MonetaryUnit", "Bytecoin", "MonaCoin", "BitBay", "Ethereum", "Bitcoin Cash", "NEM", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "Gulden", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Crown", "Sprouts", "ION", "Clams", "OKCash", "Diamond", "Skycoin", "SpreadCoin", "Expanse", "SIBCoin", "ZenCash", "Radium", "LBRY Credits", "Shift", "DigitalNote", "Neblio", "Compcoin", "Omni", "ATC Coin", "Gambit", "E-coin", "SaluS", "Golos", "GridCoin"]
,
 ["Burst", "Einsteinium", "Ripple", "BitShares", "Stellar Lumens", "Nxt", "Viacoin", "ReddCoin", "Counterparty", "Litecoin", "Vertcoin", "Mooncoin", "Rubycoin", "Dogecoin", "Blocknet", "I-O Coin", "OKCash", "Groestlcoin", "BlackCoin", "Peercoin", "Unobtanium", "PotCoin", "DigitalNote", "Energycoin", "Dash", "Syscoin", "NAV Coin", "CloakCoin", "MonaCoin", "Namecoin", "Bitcoin", "Monero", "Bytecoin", "FairCoin", "Gulden", "BitBay", "MonetaryUnit", "Ethereum", "Bitcoin Cash", "NEM", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Crown", "Sprouts", "ION", "Clams", "Diamond", "Skycoin", "SpreadCoin", "Expanse", "SIBCoin", "ZenCash", "Radium", "LBRY Credits", "Shift", "Neblio", "Compcoin", "Omni", "ATC Coin", "Gambit", "E-coin", "SaluS", "Golos", "GridCoin"]
,
 ["Nxt", "Einsteinium", "Ripple", "Litecoin", "I-O Coin", "Counterparty", "Viacoin", "BitShares", "Dogecoin", "Verge", "ReddCoin", "Mooncoin", "Rubycoin", "Bytecoin", "Stellar Lumens", "MonaCoin", "Burst", "DigitalNote", "Energycoin", "Groestlcoin", "BlackCoin", "Bitcoin", "Vertcoin", "Gulden", "CloakCoin", "Peercoin", "Namecoin", "Unobtanium", "Dash", "Monero", "NAV Coin", "Clams", "OKCash", "PotCoin", "Blocknet", "BitBay", "MonetaryUnit", "Ethereum", "Bitcoin Cash", "NEM", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Syscoin", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "FairCoin", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Crown", "Sprouts", "ION", "Diamond", "Skycoin", "SpreadCoin", "Expanse", "SIBCoin", "ZenCash", "Radium", "LBRY Credits", "Shift", "Neblio", "Compcoin", "Omni", "ATC Coin", "Gambit", "E-coin", "SaluS", "Golos", "GridCoin"]
,
 ["BitShares", "Stellar Lumens", "Burst", "Einsteinium", "Ripple", "Nxt", "Viacoin", "ReddCoin", "Counterparty", "Mooncoin", "Litecoin", "Dogecoin", "I-O Coin", "PotCoin", "Blocknet", "Rubycoin", "BlackCoin", "Vertcoin", "Peercoin", "Unobtanium", "DigitalNote", "Groestlcoin", "Dash", "Bytecoin", "NAV Coin", "FairCoin", "CloakCoin", "MonaCoin", "Namecoin", "Energycoin", "Bitcoin", "Monero", "Syscoin", "Gulden", "BitBay", "MonetaryUnit", "Ethereum", "Bitcoin Cash", "NEM", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Crown", "Sprouts", "ION", "Clams", "OKCash", "Diamond", "Skycoin", "SpreadCoin", "Expanse", "SIBCoin", "ZenCash", "Radium", "LBRY Credits", "Shift", "Neblio", "Compcoin", "Omni", "ATC Coin", "Gambit", "E-coin", "SaluS", "Golos", "GridCoin"]
,
 ["Dogecoin", "Stellar Lumens", "Nxt", "Peercoin", "Mooncoin", "BlackCoin", "Ripple", "Litecoin", "Bitcoin", "Dash", "ReddCoin", "Viacoin", "Namecoin", "FairCoin", "MonaCoin", "NAV Coin", "PotCoin", "Monero", "BitShares", "Counterparty", "Unobtanium", "Bytecoin", "I-O Coin", "MonetaryUnit", "Einsteinium", "Rubycoin", "Syscoin", "Verge", "Vertcoin", "CloakCoin", "BitBay", "DigitalNote", "Energycoin", "Ethereum", "Bitcoin Cash", "NEM", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Factom", "Byteball Bytes", "Nexus", "Siacoin", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Lykke", "Blocknet", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "Gulden", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Emercoin", "Crown", "Sprouts", "ION", "Clams", "OKCash", "Diamond", "Skycoin", "SpreadCoin", "Expanse", "SIBCoin", "ZenCash", "Radium", "Burst", "LBRY Credits", "Shift", "Neblio", "Compcoin", "Omni", "ATC Coin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "Golos", "GridCoin"]
,
 ["I-O Coin", "Burst", "NAV Coin", "Viacoin", "Monero", "Counterparty", "Einsteinium", "Blocknet", "Dash", "Factom", "OKCash", "Bytecoin", "BitBay", "DigitalNote", "Bitcoin", "FairCoin", "LEOcoin", "PotCoin", "Energycoin", "Gulden", "Omni", "Nexus", "Siacoin", "BitcoinDark", "GameCredits", "MonetaryUnit", "Ethereum", "Syscoin", "Nxt", "Peercoin", "MonaCoin", "Namecoin", "Shift", "NEM", "BitShares", "CloakCoin", "ReddCoin", "Emercoin", "Expanse", "SIBCoin", "Bitcoin Cash", "Ripple", "Litecoin", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Stellar Lumens", "Hshare", "Komodo", "PIVX", "Byteball Bytes", "DigiByte", "GXShares", "Lykke", "Dogecoin", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Vertcoin", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "DECENT", "The ChampCoin", "Crown", "Sprouts", "ION", "Clams", "Unobtanium", "Diamond", "Skycoin", "SpreadCoin", "Mooncoin", "ZenCash", "Radium", "LBRY Credits", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "BlackCoin", "Golos", "GridCoin"]
,
 ["I-O Coin", "Burst", "NAV Coin", "Viacoin", "Counterparty", "Monero", "Blocknet", "Dash", "Factom", "FairCoin", "OKCash", "Einsteinium", "Bytecoin", "DigitalNote", "BitBay", "Bitcoin", "Gulden", "PotCoin", "Energycoin", "Syscoin", "Shift", "Ethereum", "Nexus", "Siacoin", "BitcoinDark", "GameCredits", "ReddCoin", "NEM", "Nxt", "Peercoin", "MonaCoin", "Namecoin", "Omni", "BitShares", "CloakCoin", "Emercoin", "SIBCoin", "Bitcoin Cash", "Ripple", "Litecoin", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Stellar Lumens", "Hshare", "Komodo", "PIVX", "Byteball Bytes", "DigiByte", "GXShares", "Lykke", "Dogecoin", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Vertcoin", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Crown", "Sprouts", "ION", "Clams", "Unobtanium", "Diamond", "Skycoin", "MonetaryUnit", "SpreadCoin", "Mooncoin", "Expanse", "ZenCash", "Radium", "LBRY Credits", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "BlackCoin", "Golos", "GridCoin"]
,
 ["I-O Coin", "LEOcoin", "Viacoin", "Burst", "NAV Coin", "Blocknet", "MonetaryUnit", "Einsteinium", "Monero", "Factom", "Counterparty", "OKCash", "Dash", "Bytecoin", "BitBay", "PotCoin", "Energycoin", "Bitcoin", "FairCoin", "DigitalNote", "Omni", "GameCredits", "Gulden", "Ethereum", "Nexus", "Siacoin", "Nxt", "Peercoin", "MonaCoin", "Namecoin", "Shift", "NEM", "BitShares", "BitcoinDark", "Syscoin", "CloakCoin", "ReddCoin", "Emercoin", "Expanse", "SIBCoin", "Bitcoin Cash", "Ripple", "Litecoin", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Stellar Lumens", "Hshare", "Komodo", "PIVX", "Byteball Bytes", "DigiByte", "GXShares", "Lykke", "Dogecoin", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Vertcoin", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "DECENT", "The ChampCoin", "Crown", "Sprouts", "ION", "Clams", "Unobtanium", "Diamond", "Skycoin", "SpreadCoin", "Mooncoin", "ZenCash", "Radium", "LBRY Credits", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "BlackCoin", "Golos", "GridCoin"]
,
 ["I-O Coin", "Burst", "Viacoin", "Blocknet", "NAV Coin", "Dash", "Factom", "Einsteinium", "Monero", "Counterparty", "OKCash", "BitBay", "Expanse", "PotCoin", "Bytecoin", "Stellar Lumens", "DigitalNote", "Energycoin", "Bitcoin", "Syscoin", "FairCoin", "Gulden", "MonetaryUnit", "Shift", "Nexus", "Siacoin", "BitcoinDark", "GameCredits", "NEM", "Nxt", "Peercoin", "MonaCoin", "Namecoin", "Omni", "Ethereum", "Litecoin", "ReddCoin", "Emercoin", "Bitcoin Cash", "Ripple", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "BitShares", "Hshare", "Komodo", "PIVX", "Byteball Bytes", "DigiByte", "GXShares", "Lykke", "Dogecoin", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Vertcoin", "Bitdeal", "Metaverse ETP", "ZCoin", "CloakCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "DECENT", "The ChampCoin", "Crown", "Sprouts", "ION", "Clams", "Unobtanium", "Diamond", "Skycoin", "SpreadCoin", "Mooncoin", "SIBCoin", "ZenCash", "Radium", "LBRY Credits", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "BlackCoin", "Golos", "GridCoin", "LEOcoin"]
,
 ["I-O Coin", "Burst", "NAV Coin", "Viacoin", "Einsteinium", "Monero", "Blocknet", "Counterparty", "Dash", "Factom", "OKCash", "Bytecoin", "FairCoin", "DigitalNote", "BitBay", "PotCoin", "Bitcoin", "Energycoin", "Gulden", "MonetaryUnit", "Omni", "Nexus", "Siacoin", "BitcoinDark", "GameCredits", "Ethereum", "Syscoin", "Nxt", "Peercoin", "LEOcoin", "MonaCoin", "Namecoin", "Shift", "NEM", "BitShares", "CloakCoin", "ReddCoin", "Emercoin", "Expanse", "SIBCoin", "Bitcoin Cash", "Ripple", "Litecoin", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Stellar Lumens", "Hshare", "Komodo", "PIVX", "Byteball Bytes", "DigiByte", "GXShares", "Lykke", "Dogecoin", "Verge", "FirstCoin", "Ubiq", "Particl", "Rise", "Vertcoin", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "DECENT", "The ChampCoin", "Crown", "Sprouts", "ION", "Clams", "Unobtanium", "Diamond", "Skycoin", "SpreadCoin", "Mooncoin", "ZenCash", "Radium", "LBRY Credits", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "BlackCoin", "Golos", "GridCoin"]
,
 ["Shift", "Nxt", "Monero", "Counterparty", "Namecoin", "Bitcoin", "I-O Coin", "Dash", "NEM", "BitShares", "Factom", "NAV Coin", "Viacoin", "Ethereum", "Ripple", "Verge", "FairCoin", "CloakCoin", "Clams", "BitBay", "Burst", "BlackCoin", "GridCoin", "LEOcoin", "Litecoin", "Blocknet", "Gulden", "MonaCoin", "MonetaryUnit", "SIBCoin", "Energycoin", "Bytecoin", "Stellar Lumens", "Dogecoin", "Vertcoin", "Peercoin", "Emercoin", "OKCash", "Unobtanium", "Expanse", "DigitalNote", "Nexus", "Siacoin", "GameCredits", "Syscoin", "ReddCoin", "Diamond", "PotCoin", "Omni", "Rubycoin", "Mooncoin", "Einsteinium", "Bitcoin Cash", "IOTA", "Ethereum Classic", "NEO", "BitConnect", "Lisk", "Zcash", "Stratis", "Waves", "Ark", "Steem", "Decred", "Hshare", "Komodo", "PIVX", "Byteball Bytes", "DigiByte", "BitcoinDark", "GXShares", "Lykke", "FirstCoin", "Ubiq", "Particl", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "DECENT", "The ChampCoin", "Crown", "Sprouts", "ION", "Skycoin", "SpreadCoin", "ZenCash", "Radium", "LBRY Credits", "Neblio", "Compcoin", "ATC Coin", "Gambit", "E-coin", "SaluS", "Groestlcoin", "Golos"]
,
 ["Steem", "Zcash", "Lykke", "Radium", "Factom", "Ethereum", "BitBay", "Waves", "Gambit", "Decred", "Expanse", "Ethereum Classic", "Shift", "Nxt", "Gulden", "LBRY Credits", "Stratis", "Vertcoin", "Counterparty", "Unobtanium", "Bitcoin", "Dash", "Omni", "BlackCoin", "Blocknet", "Diamond", "Emercoin", "GridCoin", "Syscoin", "SpreadCoin", "PotCoin", "Einsteinium", "Litecoin", "NEM", "Lisk", "BitShares", "Clams", "Dogecoin", "ReddCoin", "MonetaryUnit", "Burst", "Energycoin", "Monero", "FairCoin", "MonaCoin", "Byteball Bytes", "I-O Coin", "Peercoin", "Viacoin", "Namecoin", "SaluS", "Crown", "DigitalNote", "Ripple", "Bytecoin", "Stellar Lumens", "PIVX", "Nexus", "Siacoin", "Verge", "NoLimitCoin", "Bitcoin Cash", "IOTA", "NEO", "BitConnect", "Ark", "Hshare", "Komodo", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "FirstCoin", "Ubiq", "Particl", "NAV Coin", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "CloakCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "ION", "OKCash", "Skycoin", "Mooncoin", "SIBCoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Groestlcoin", "Golos"]
,
 ["Zcash", "Steem", "Lykke", "Ethereum", "Factom", "BitBay", "Radium", "Expanse", "Ethereum Classic", "Waves", "Decred", "Nxt", "Dash", "Stratis", "Gambit", "Vertcoin", "Counterparty", "PotCoin", "Shift", "BlackCoin", "Bitcoin", "Unobtanium", "LBRY Credits", "Blocknet", "Emercoin", "MonetaryUnit", "Litecoin", "Diamond", "SpreadCoin", "NEM", "Dogecoin", "Viacoin", "Einsteinium", "Lisk", "BitShares", "FairCoin", "ReddCoin", "Omni", "Syscoin", "Burst", "Monero", "Peercoin", "GridCoin", "Ripple", "Bytecoin", "PIVX", "Byteball Bytes", "Crown", "Namecoin", "Clams", "Verge", "MonaCoin", "DigitalNote", "Stellar Lumens", "Nexus", "Siacoin", "NoLimitCoin", "Bitcoin Cash", "IOTA", "NEO", "BitConnect", "Ark", "Hshare", "Komodo", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "FirstCoin", "I-O Coin", "Ubiq", "Particl", "NAV Coin", "Rise", "Bitdeal", "Metaverse ETP", "Gulden", "ZCoin", "CloakCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "ION", "OKCash", "Skycoin", "Mooncoin", "SIBCoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Energycoin", "Rubycoin", "E-coin", "SaluS", "Groestlcoin", "Golos"]
,
 ["Steem", "Zcash", "Factom", "Lykke", "Radium", "Ethereum", "BitBay", "Waves", "Decred", "Expanse", "Shift", "Vertcoin", "Gambit", "Ethereum Classic", "Gulden", "Counterparty", "Stratis", "Omni", "Bitcoin", "Dash", "Nxt", "Unobtanium", "Diamond", "BlackCoin", "LBRY Credits", "GridCoin", "Litecoin", "Blocknet", "Emercoin", "ReddCoin", "SpreadCoin", "Burst", "NEM", "BitShares", "Dogecoin", "Syscoin", "Clams", "MonetaryUnit", "PotCoin", "Lisk", "Viacoin", "Einsteinium", "Energycoin", "Monero", "Bytecoin", "FairCoin", "I-O Coin", "Peercoin", "Namecoin", "DigitalNote", "SaluS", "Byteball Bytes", "MonaCoin", "Mooncoin", "Ripple", "PIVX", "Nexus", "Siacoin", "Crown", "SIBCoin", "Groestlcoin", "Bitcoin Cash", "IOTA", "NEO", "BitConnect", "Ark", "Stellar Lumens", "Hshare", "Komodo", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "Verge", "FirstCoin", "Ubiq", "Particl", "NAV Coin", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "CloakCoin", "NoLimitCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "ION", "OKCash", "Skycoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Golos"]
,
 ["Zcash", "Steem", "Ethereum", "Decred", "Radium", "Factom", "BitBay", "Waves", "Expanse", "Gambit", "Ethereum Classic", "Stratis", "Gulden", "Unobtanium", "Bitcoin", "Nxt", "Shift", "Dash", "Byteball Bytes", "Vertcoin", "LBRY Credits", "Counterparty", "Blocknet", "Diamond", "Omni", "Energycoin", "BlackCoin", "Litecoin", "NEM", "Lykke", "ReddCoin", "SpreadCoin", "PotCoin", "GridCoin", "Lisk", "Syscoin", "Viacoin", "Emercoin", "Clams", "MonetaryUnit", "Einsteinium", "BitShares", "Dogecoin", "Burst", "Monero", "MonaCoin", "Crown", "I-O Coin", "FairCoin", "ZCoin", "Peercoin", "Namecoin", "DigitalNote", "SaluS", "Bytecoin", "Mooncoin", "Ripple", "Stellar Lumens", "PIVX", "Nexus", "Siacoin", "Verge", "NoLimitCoin", "Bitcoin Cash", "IOTA", "NEO", "BitConnect", "Ark", "Hshare", "Komodo", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "FirstCoin", "Ubiq", "Particl", "NAV Coin", "Rise", "Bitdeal", "Metaverse ETP", "CloakCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "ION", "OKCash", "Skycoin", "SIBCoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Groestlcoin", "Golos"]
,
 ["Steem", "Zcash", "Lykke", "Radium", "Factom", "Ethereum", "BitBay", "Waves", "Decred", "Expanse", "Gambit", "Shift", "Ethereum Classic", "Nxt", "Vertcoin", "Gulden", "Stratis", "Counterparty", "Unobtanium", "LBRY Credits", "BlackCoin", "Dash", "Omni", "Bitcoin", "Blocknet", "Diamond", "Einsteinium", "GridCoin", "Syscoin", "Emercoin", "SpreadCoin", "PotCoin", "NEM", "Lisk", "BitShares", "Dogecoin", "ReddCoin", "Energycoin", "Litecoin", "Clams", "MonetaryUnit", "Burst", "Monero", "FairCoin", "MonaCoin", "Byteball Bytes", "I-O Coin", "Peercoin", "Namecoin", "SaluS", "Bytecoin", "Viacoin", "DigitalNote", "Ripple", "Stellar Lumens", "PIVX", "Nexus", "Siacoin", "Verge", "NoLimitCoin", "Crown", "Bitcoin Cash", "IOTA", "NEO", "BitConnect", "Ark", "Hshare", "Komodo", "DigiByte", "BitcoinDark", "GameCredits", "GXShares", "FirstCoin", "Ubiq", "Particl", "NAV Coin", "Rise", "Bitdeal", "Metaverse ETP", "ZCoin", "CloakCoin", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "ION", "OKCash", "Skycoin", "Mooncoin", "SIBCoin", "ZenCash", "Neblio", "Compcoin", "ATC Coin", "Rubycoin", "E-coin", "Groestlcoin", "Golos"]
,
 ["Bitcoin", "Waves", "Zcash", "Gulden", "Lykke", "LBRY Credits", "Litecoin", "Shift", "Lisk", "Verge", "DigitalNote", "Ethereum", "Stratis", "Syscoin", "Emercoin", "Monero", "MonaCoin", "Steem", "Blocknet", "ReddCoin", "BitBay", "Dash", "NAV Coin", "NoLimitCoin", "NEM", "Ethereum Classic", "Dogecoin", "Counterparty", "BitShares", "Factom", "Peercoin", "Mooncoin", "NEO", "Viacoin", "SpreadCoin", "Byteball Bytes", "ZCoin", "Unobtanium", "Rise", "CloakCoin", "BlackCoin", "Stellar Lumens", "Namecoin", "Radium", "Burst", "Ripple", "Bytecoin", "Decred", "I-O Coin", "FairCoin", "Crown", "Energycoin", "Gambit", "Groestlcoin", "PIVX", "Nexus", "Siacoin", "DigiByte", "GameCredits", "Vertcoin", "Clams", "OKCash", "MonetaryUnit", "Einsteinium", "Bitcoin Cash", "IOTA", "BitConnect", "Ark", "Hshare", "Komodo", "BitcoinDark", "GXShares", "FirstCoin", "Nxt", "Ubiq", "Particl", "Bitdeal", "Metaverse ETP", "Elastic", "Aidos Kuneen", "LEOcoin", "DECENT", "The ChampCoin", "Sprouts", "ION", "Diamond", "Skycoin", "Expanse", "SIBCoin", "ZenCash", "PotCoin", "Neblio", "Compcoin", "Omni", "ATC Coin", "Rubycoin", "E-coin", "SaluS", "Golos", "GridCoin"]
];



/*
card_list=
my_list=[]
for(i=0;i<100;i++){my_list.push([matrix_of_simil_CARD[0][i],M_CAP_ordered_list[i]])}
my_list.sort(function(a,b){ return b[0]-a[0];})
test_list=[]
for(j=0;j<100;j++){test_list.push(my_list[j][1])}
*/